$pdf_mode = 1;               # tex -> pdf
$auto_rc_use = 1;            # Do not read further latexmkrc files
$out_dir = "..";             # Create output files in the assignment directory (assignment/)
$warnings_as_errors = 1;     # Elevates warnings to errors.  Enforces cleaner code.
$pdflatex = "pdflatex -halt-on-error -interaction=batchmode %O %S";
                             # Forces latexmk to stop and quit if it encounters an error
                             