name: XCS221
channels:
  - defaults
dependencies:
  - python=3.8
  - cmake=3.22.1
  - boost=1.73
  - notebook=6.5.4
  - tk>=8.6.8
  - matplotlib=3.5.3
  - plotly=5.19.0
  - pandas=1.5.3
  - pip=23.3.1
  - pip:
    - osmium==3.7.0
    - cloudpickle==2.0.0
    - cycler==0.11.0
    - gymnasium==0.28.1
    - importlib-metadata==6.7.0
    - jax-jumpy==1.0.0
    - kiwisolver==1.4.5
    - matplotlib==3.5.3
    - numpy==1.21.6
    - packaging==23.1
    - Pillow==9.5.0
    - pygame==2.5.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - six==1.16.0
    - typing_extensions==4.7.1
    - zipp==3.15.0
    - keyboard==0.13.5